services:
  - type: web
    name: match-streams-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python main.py
    autoDeploy: false
